// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsGOks1kgcxnFJ9vDX1saUYLkQ1TOTrZk',
    appId: '1:1084450087484:web:614873547c68f05a9d1939',
    messagingSenderId: '1084450087484',
    projectId: 'fir-notes-app-f4cf2',
    authDomain: 'fir-notes-app-f4cf2.firebaseapp.com',
    storageBucket: 'fir-notes-app-f4cf2.firebasestorage.app',
    measurementId: 'G-48TYWTY0L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg8_c2u9NzOGXlvJQFwh-4AQpvip4rcHc',
    appId: '1:1084450087484:android:5a54b730222b5a5c9d1939',
    messagingSenderId: '1084450087484',
    projectId: 'fir-notes-app-f4cf2',
    storageBucket: 'fir-notes-app-f4cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBbQJIDNI0c5IbGMqW35H-uxk1-YVTHTg',
    appId: '1:1084450087484:ios:e812dd89bafb33379d1939',
    messagingSenderId: '1084450087484',
    projectId: 'fir-notes-app-f4cf2',
    storageBucket: 'fir-notes-app-f4cf2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBbQJIDNI0c5IbGMqW35H-uxk1-YVTHTg',
    appId: '1:1084450087484:ios:e812dd89bafb33379d1939',
    messagingSenderId: '1084450087484',
    projectId: 'fir-notes-app-f4cf2',
    storageBucket: 'fir-notes-app-f4cf2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsGOks1kgcxnFJ9vDX1saUYLkQ1TOTrZk',
    appId: '1:1084450087484:web:4e88e4ddc5129cf69d1939',
    messagingSenderId: '1084450087484',
    projectId: 'fir-notes-app-f4cf2',
    authDomain: 'fir-notes-app-f4cf2.firebaseapp.com',
    storageBucket: 'fir-notes-app-f4cf2.firebasestorage.app',
    measurementId: 'G-6WNKFD1PW8',
  );

}